SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II 
JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
LEFT JOIN ITEM_TREE IT2
ON IT2.PARENT_ITEM_ID = II.ITEM_ID
WHERE IT2.ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC