SELECT ID, COALESCE(PA.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA 
LEFT JOIN (
    SELECT PARENT_ID, COUNT(PARENT_ID) AS CNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
) AS PA
ON ID = PA.PARENT_ID
ORDER BY ID
