SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
FROM REST_INFO 
GROUP BY FOOD_TYPE) R2
ON R.FOOD_TYPE = R2.FOOD_TYPE
WHERE R2.MF = R.FAVORITES
ORDER BY R.FOOD_TYPE DESC

