# 1번방법
SELECT A.ID, 
CASE 
    WHEN T.NG = 1 THEN 'CRITICAL'
    WHEN T.NG = 2 THEN 'HIGH'
    WHEN T.NG = 3 THEN 'MEDIUM'
    WHEN T.NG = 4 THEN 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA A
JOIN 
(
    SELECT NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS NG, ID
    FROM ECOLI_DATA
) AS T
ON A.ID = T.ID

# 2번방법
# SELECT A.ID, 
# CASE 
#     WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
#     WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
#     WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
#     WHEN NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) = 4 THEN 'LOW'
# END AS COLONY_NAME
# FROM ECOLI_DATA A
# ORDER BY A.ID ASC