# SELECT 
# CASE
#     WHEN
#     CNT.CNT * 0.25
    
# FROM ECOLI_DATA E

# (SELECT COUNT(ID) AS CNT
# FROM ECOLI_DATA) AS CNT

# ORDER BY E.SIZE_OF_COLONY DESC

# SELECT ID
# FROM ECOLI_DATA 
# ORDER BY SIZE_OF_COLONY
# LIMIT COUNT(*)

SELECT A.ID, 
CASE 
    WHEN T.NG = 1 THEN 'CRITICAL'
    WHEN T.NG = 2 THEN 'HIGH'
    WHEN T.NG = 3 THEN 'MEDIUM'
    WHEN T.NG = 4 THEN 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA A
JOIN 
(
    SELECT NTILE(4) OVER(ORDER BY SIZE_OF_COLONY DESC) AS NG, ID
    FROM ECOLI_DATA
) AS T
ON A.ID = T.ID