SELECT DISTINCT
    A.WRITER_ID AS USER_ID,
    C.NICKNAME,
    CONCAT(C.CITY, ' ', C.STREET_ADDRESS1, ' ', C.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(C.TLNO, 1, 3), '-', SUBSTR(C.TLNO, 4, 4), '-', SUBSTR(C.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD A
JOIN 
    (SELECT WRITER_ID
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3) B
ON A.WRITER_ID = B.WRITER_ID
JOIN USED_GOODS_USER C
ON A.WRITER_ID = C.USER_ID
ORDER BY A.WRITER_ID DESC
