SELECT YEAR(S.sales_date), MONTH(S.sales_date), COUNT(DISTINCT S.user_id) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT S.user_id)/(
    SELECT COUNT(USER_ID)
    FROM USER_INFO  
    WHERE YEAR(JOINED) = '2021'
), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U ON S.USER_ID = U.USER_ID
WHERE YEAR(U.JOINED) = '2021'
GROUP BY YEAR(S.sales_date), MONTH(S.sales_date)
ORDER BY YEAR(S.sales_date) ASC, MONTH(S.sales_date) ASC 



