SELECT HISTORY_ID, 
    CASE 
        WHEN RENTAL_DATE >= 90 
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')) / 100 * RENTAL_DATE * daily_fee)
        WHEN RENTAL_DATE >= 30
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')) / 100 * RENTAL_DATE * daily_fee)
        WHEN RENTAL_DATE >= 7
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')) / 100 * RENTAL_DATE * daily_fee)
        ELSE RENTAL_DATE * daily_fee
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT H.HISTORY_ID, H.CAR_ID, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
) AS HT ON C.CAR_ID = HT.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC