# SELECT H.HISTORY_ID, 
# CASE 
#     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE * 0.9)
#     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE * 0.93)
#     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE * 0.95)
#     ELSE ROUND((DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE)
# END AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
# WHERE C.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, H.HISTORY_ID DESC

# (
#     SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE CAR_TYPE = '트럭'
#     ORDER BY DURATION_TYPE
# )


SELECT HISTORY_ID, 
    CASE 
        WHEN RENTAL_DATE >= 90 
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')) / 100 * RENTAL_DATE * daily_fee)
        WHEN RENTAL_DATE >= 30
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')) / 100 * RENTAL_DATE * daily_fee)
        WHEN RENTAL_DATE >= 7
        THEN ROUND((100 - (SELECT DISCOUNT_RATE 
                    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
                    WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')) / 100 * RENTAL_DATE * daily_fee)
        ELSE RENTAL_DATE * daily_fee
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT H.HISTORY_ID, H.CAR_ID, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
) AS HT ON C.CAR_ID = HT.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC