SELECT F.FLAVOR AS FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
    FROM JULY
    GROUP BY FLAVOR
) AS T
ON F.FLAVOR = T.FLAVOR
ORDER BY (F.TOTAL_ORDER + T.TOT) DESC 
LIMIT 3



