WITH RECURSIVE TIMETABLE (HOUR) AS (
    SELECT 0
    UNION
    SELECT HOUR + 1 FROM TIMETABLE WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(O.ANIMAL_ID)
FROM TIMETABLE T
LEFT JOIN ANIMAL_OUTS O ON T.HOUR = HOUR(O.DATETIME)
GROUP BY T.HOUR