SELECT YEAR(E1.DIFFERENTIATION_DATE) AS YEAR, E2.SIZE_OF_COLONY - E1.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E1
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS E2
ON YEAR(E1.DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC