SELECT B.CATEGORY AS TOTAL_SALES, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE MONTH(S.SALES_DATE) = 1 AND YEAR(S.SALES_DATE) = 2022
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC