SELECT F.CATEGORY, F.PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN  
(
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
    GROUP BY CATEGORY
)  AS B
ON F.CATEGORY = B.CATEGORY AND F.PRICE = B.PRICE
ORDER BY F.PRICE DESC