SELECT COUNT(*) AS FISH_COUNT, AL.MAX_LENGTH AS MAX_LENGTH, FI.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO AS FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(IF(LENGTH <= 10, 10, LENGTH)) >= 33
) AS AL
ON FI.FISH_TYPE = AL.FISH_TYPE
GROUP BY FI.FISH_TYPE
ORDER BY FI.FISH_TYPE ASC